name: harmonic_extension
channels:
  - conda-forge
  - pytorch
  - pyg
dependencies:
  - pip=21.3.1
  - python=3.9.9
  - pytorch=2.0.0
  - pip: 
    - pyg
    - torch-geometric
    - ninja
    - easydict
    - pyyaml
    - pykeen 
    - ogb==1.3.2
